"""Convert a boot-video mp4 into what the app plays at start-up.

Run once after changing the video (needs ffmpeg + ffprobe on PATH):

    python tools/build_intro.py                 # assets/gb_intro.mp4
    python tools/build_intro.py orig_gb_intro   # a local assets/orig_gb_intro.mp4

Writes, next to the mp4 and with the same stem,
  <stem>.npz   frames (N, 144, 160, 3) uint8 at Game Boy resolution, fps, and
               idle_index = last frame on which the logo is still visible
               (used as the "No video" screen)
  <stem>.wav   the soundtrack, mono 22.05 kHz 16-bit

The app itself needs neither ffmpeg nor the mp4; it reads the npz and wav.
The shipped gb_intro.* files are generated by tools/make_intro.py instead;
this converter is for a replacement clip of your own.
"""
import json
import subprocess
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
STEM = sys.argv[1] if len(sys.argv) > 1 else "gb_intro"
SRC = ROOT / "assets" / f"{STEM}.mp4"
NPZ = ROOT / "assets" / f"{STEM}.npz"
WAV = ROOT / "assets" / f"{STEM}.wav"
W, H = 160, 144


def probe_fps(path: Path) -> float:
    out = subprocess.run(["ffprobe", "-v", "error", "-select_streams", "v:0", "-show_entries",
                          "stream=r_frame_rate", "-of", "json", str(path)],
                         check=True, capture_output=True, text=True).stdout
    num, den = json.loads(out)["streams"][0]["r_frame_rate"].split("/")
    return float(num) / float(den)


def main() -> None:
    if not SRC.exists():
        sys.exit(f"missing {SRC}")
    fps = probe_fps(SRC)
    raw = subprocess.run(
        ["ffmpeg", "-v", "error", "-i", str(SRC), "-vf", f"scale={W}:{H}:flags=neighbor",
         "-f", "rawvideo", "-pix_fmt", "rgb24", "-"], check=True, capture_output=True).stdout
    frames = np.frombuffer(raw, dtype=np.uint8).reshape(-1, H, W, 3)
    # Last frame on which the logo is drawn at full strength (the video fades
    # out afterwards): pixels as dark as the darkest pixel in the whole clip.
    sums = frames.astype(np.int16).sum(axis=3).reshape(len(frames), -1)
    darkest = int(sums.min())
    solid = (sums <= darkest + 30).any(axis=1)
    idle_index = int(np.nonzero(solid)[0][-1]) if solid.any() else len(frames) - 1
    np.savez_compressed(NPZ, frames=frames, fps=np.float32(fps), idle_index=np.int32(idle_index))
    subprocess.run(["ffmpeg", "-v", "error", "-y", "-i", str(SRC), "-vn", "-ac", "1", "-ar", "22050",
                    "-sample_fmt", "s16", str(WAV)], check=True)
    print(f"{NPZ.name}: {len(frames)} frames @ {fps:.2f} fps, idle frame {idle_index} "
          f"({idle_index / fps:.2f} s), {NPZ.stat().st_size // 1024} KB")
    print(f"{WAV.name}: {WAV.stat().st_size // 1024} KB")


if __name__ == "__main__":
    main()
